---
- name: Generate Diffie-Hellman parameters if needed
  command:
    cmd: openssl dhparam -out "{{ reverse_proxy_dhparam_path }}" "{{ reverse_proxy_dhparam_size }}"
    creates: "{{ reverse_proxy_dhparam_path }}"
  notify: Reload nginx
